[package]
name = "cfd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray={version = "0.15", features=["rayon"]}
rayon="1.5"
itertools="0.10.2"
